const fs = require('fs');
const path = require('path');
const { chromium } = require('playwright');
const URL = process.env.BI_TEST_URL || 'http://127.0.0.1:8765/';
const OUT = path.resolve('e2e-artifacts');
fs.mkdirSync(OUT, { recursive: true });
function check(condition, message) { if (!condition) throw new Error(message); }
async function main() {
  const browser = await chromium.launch({ headless: true, executablePath: process.env.BI_TEST_CHROME || undefined });
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1, acceptDownloads: true });
  const errors = [];
  page.on('pageerror', e => errors.push(e.stack || e.message));
  await page.goto(URL, { waitUntil: 'domcontentloaded', timeout: 60000 });
  await page.waitForSelector('#comando .cmd', { timeout: 30000 });
  check(await page.locator('#biTerritorialShared').isVisible(), 'Faixa de filtros compartilhados ausente');
  await page.locator('#biShareRegion').selectOption('Norte');
  await page.locator('#biShareUF').selectOption('RR');
  await page.waitForFunction(() => document.querySelector('#uf')?.value === 'RR');
  await page.screenshot({ path: path.join(OUT, '01-home.png'), fullPage: true });
  const pre = await page.evaluate(() => ({ body: document.body.innerText, legacyPrint: typeof window.v73Print, icon: !!document.getElementById('cmdRepresentacaoInstitucional') }));
  check(pre.icon, 'Ícone Representação Institucional ausente na home');
  check(!pre.body.includes('window.v73Print=function'), 'HTML exibe JavaScript v73 como texto');
  check(pre.legacyPrint === 'function', 'Rotina de impressão legada v73 não carregou');
  await page.locator('#cmdRepresentacaoInstitucional').click();
  await page.waitForFunction(() => document.querySelector('#riUF')?.value === 'RR');
  check(await page.locator('#riRegiao').inputValue() === 'Norte', 'Região compartilhada não propagou para Representação Institucional');
  await page.locator('#biShareClear').click();
  await page.waitForFunction(() => document.querySelector('#riUF')?.value === 'TODOS');
  await page.waitForSelector('#riResults table tbody tr', { timeout: 30000 });
  const n = await page.locator('#riResults table tbody tr').count();
  check(n === 843, 'Base institucional retornou ' + n + ' registros; esperado 843');
  await page.screenshot({ path: path.join(OUT, '02-representacao.png'), fullPage: true });
  await page.locator('#riRegiao').selectOption('Norte');
  await page.locator('#riUF').selectOption('RR');
  const selected = await page.locator('#riResults').innerText();
  check(/Marcos Jorge/i.test(selected), 'Marcos Jorge não aparece para RR em 2027');
  check(selected.includes('REPUBLICANOS'), 'Partido REPUBLICANOS não encontrado');
  await page.screenshot({ path: path.join(OUT, '03-roraima.png'), fullPage: true });
  const [report] = await Promise.all([page.waitForEvent('popup'), page.locator('#riReport').click()]);
  await report.waitForFunction(() => document.body.innerText.includes('RELATÓRIO EXECUTIVO — REPRESENTAÇÃO INSTITUCIONAL'), { timeout: 30000 });
  const reportText = await report.locator('body').innerText();
  check(reportText.includes('REPRESENTAÇÃO INSTITUCIONAL'), 'Relatório institucional não abriu');
  check(reportText.includes('Marcos Jorge'), 'Relatório de RR perdeu Marcos Jorge');
  check(reportText.includes('Contexto hidroviário territorial'), 'Relatório não incluiu o contexto técnico de investimentos e sugestões');
  await report.screenshot({ path: path.join(OUT, '04-relatorio-institucional.png'), fullPage: true });
  await report.close();
  const [brief] = await Promise.all([page.waitForEvent('popup'), page.locator('#riBriefing').click()]);
  await brief.waitForFunction(() => document.body.innerText.includes('BRIEFING EXECUTIVO — REPRESENTAÇÃO INSTITUCIONAL'), { timeout: 30000 });
  check((await brief.locator('body').innerText()).includes('BRIEFING'), 'Briefing não abriu');
  await brief.screenshot({ path: path.join(OUT, '05-briefing.png'), fullPage: true });
  await brief.close();
  await page.locator('#riPreviewButton').click();
  await page.waitForSelector('#riExecutivePreview iframe');
  check(await page.locator('#riExecutivePreview').isVisible(), 'Prévia interna do relatório não abriu');
  await page.screenshot({ path: path.join(OUT, '05b-previa-institucional.png'), fullPage: true });
  await page.locator('#riPreviewClose').click();

  // Nova página executiva no padrão modal de Sugestões de Investimentos.
  await page.locator('#riModalOpenButton').click();
  await page.waitForSelector('#riInstitutionalModal:not([hidden])');
  await page.frameLocator('#riModalFrame').locator('h1').waitFor({ timeout: 30000 });
  const modalReportText = await page.frameLocator('#riModalFrame').locator('body').innerText();
  check(modalReportText.includes('SÍNTESE EXECUTIVA'), 'Página executiva não exibe a síntese');
  check(modalReportText.includes('PONTOS PARA DECISÃO'), 'Página executiva não exibe os quadros para decisão');
  check(modalReportText.includes('Marcos Jorge'), 'Página executiva perdeu o deputado de RR');
  check(modalReportText.includes('Contexto hidroviário territorial'), 'Página executiva perdeu o cruzamento territorial');
  await page.screenshot({ path: path.join(OUT, '05c-modal-executivo.png'), fullPage: true });
  await page.evaluate(() => {
    document.getElementById('riModalFrame').contentWindow.print = function() { window.__riModalPrintVerified = true; };
  });
  await page.locator('#riModalPrint').click();
  check(await page.evaluate(() => window.__riModalPrintVerified === true), 'Botão imprimir/PDF não acionou a impressão do relatório');
  await page.locator('#riModalClose').click();
  check(!await page.locator('#riInstitutionalModal').isVisible(), 'Botão Fechar não fechou a página executiva');
  await page.locator('#riModalOpenButton').click();
  await page.waitForSelector('#riInstitutionalModal:not([hidden])');
  await page.keyboard.press('Escape');
  check(!await page.locator('#riInstitutionalModal').isVisible(), 'Tecla Escape não fechou a página executiva');
  // Filtro originado na representação deve chegar ao recorte territorial principal.
  await page.locator('#riUF').selectOption('AC');
  await page.waitForFunction(() => document.querySelector('#uf')?.value === 'AC');
  check(await page.locator('#biShareUF').inputValue() === 'AC', 'Alteração originada no módulo institucional não sincronizou o cabeçalho');
  await page.locator('#riUF').selectOption('RR');
  await page.waitForFunction(() => document.querySelector('#uf')?.value === 'RR');
  await page.locator('#homeBack button').click();
  check(await page.locator('#cmdRepresentacaoInstitucional').isVisible(), 'Retorno à home falhou');
  check(!await page.locator('#representacaoInstitucionalView').isVisible(), 'Módulo permanece visível após voltar');
  // Filtros do Recorte Territorial principal sincronizam para os demais módulos.
  await page.locator('.command-grid > button.cmd').nth(1).click();
  await page.locator('#regiao').selectOption('Sul');
  await page.waitForFunction(() => document.querySelector('#biShareRegion')?.value === 'Sul');
  await page.locator('#uf').selectOption('RS');
  await page.waitForFunction(() => document.querySelector('#riUF')?.value === 'RS');
  await page.locator('#homeBack button').click();
  await page.locator('.cmd[onclick="openPolicyPortfolio()"]').click();
  await page.waitForFunction(() => document.querySelector('#polUF')?.value === 'RS', { timeout: 30000 });
  check(await page.locator('#polRegiao').inputValue() === 'Sul', 'A base de Sugestões não herdou a região');
  await page.locator('#polRegiao').selectOption('Norte');
  await page.waitForFunction(() => document.querySelector('#regiao')?.value === 'Norte');
  await page.locator('#polUF').selectOption('AM');
  await page.waitForFunction(() => document.querySelector('#riUF')?.value === 'AM');
  check(await page.locator('#biShareUF').inputValue() === 'AM', 'UF informada no módulo de Sugestões não chegou ao cabeçalho');
  await page.locator('#polClear').click();
  await page.waitForFunction(() => document.querySelector('#riUF')?.value === 'TODOS');
  await page.screenshot({ path: path.join(OUT, '06b-sugestoes-sincronizadas.png'), fullPage: true });
  await page.locator('#policyBackHome').click();
  await page.locator('.command-grid > button.cmd').first().click();
  check(await page.locator('#quickResult').isVisible(), 'Investimentos não abriu na tabela rápida');
  await page.screenshot({ path: path.join(OUT, '06-investimentos.png'), fullPage: true });
  await page.locator('#homeBack button').click();
  await page.locator('.command-grid > button.cmd').nth(9).click();
  check(await page.locator('#docs').isVisible(), 'Relatório Executivo legado não abriu');
  check(await page.locator('#riIncludeDocs').count() === 1, 'Checkbox opcional da representação não existe');
  await page.evaluate(() => window.doc('rel'));
  check(await page.locator('#doc').count() === 1, 'Gerador de relatório legado ausente');
  await page.screenshot({ path: path.join(OUT, '07-relatorio-legado.png'), fullPage: true });
  // Conferência de responsividade em viewport móvel.
  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1 });
  await mobile.goto(URL, { waitUntil: 'domcontentloaded', timeout: 60000 });
  await mobile.waitForSelector('#biTerritorialShared');
  const bar = await mobile.locator('#biTerritorialShared').boundingBox();
  check(bar && bar.width <= 390, 'Barra de filtros não está responsiva no celular');
  await mobile.locator('#cmdRepresentacaoInstitucional').click();
  await mobile.waitForSelector('#riResults table tbody tr');
  await mobile.screenshot({ path: path.join(OUT, '08-mobile-representacao.png'), fullPage: true });
  await mobile.locator('#riModalOpenButton').click();
  await mobile.waitForSelector('#riInstitutionalModal:not([hidden])');
  await mobile.frameLocator('#riModalFrame').locator('h1').waitFor({ timeout: 30000 });
  const mobileModal = await mobile.locator('.ri-modal-dialog').boundingBox();
  check(mobileModal && mobileModal.width <= 391, 'Página executiva excede a largura de 390px no celular');
  await mobile.screenshot({ path: path.join(OUT, '09-mobile-pagina-executiva.png'), fullPage: true });
  await mobile.locator('#riModalClose').click();
  await mobile.close();
  check(errors.length === 0, 'Erros JavaScript: ' + errors.join(' | '));
  await browser.close();
  console.log(JSON.stringify({ ok: true, registros: 843, testes: ['ícone', 'sem código visível', 'v73Print', 'dados', 'filtros', 'RR', 'relatório', 'briefing', 'voltar', 'investimentos', 'relatório legado'], screenshots: 10 }, null, 2));
}
main().catch(e => { console.error('FALHA E2E:', e.stack || e); process.exit(1); });
