const fs = require('fs');
const path = require('path');
const { chromium } = require('playwright');
const URL = process.env.BI_TEST_URL || 'http://127.0.0.1:8765/';
const OUT = path.resolve('e2e-artifacts');
fs.mkdirSync(OUT, { recursive: true });
function check(condition, message) { if (!condition) throw new Error(message); }
async function main() {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1, acceptDownloads: true });
  const errors = [];
  page.on('pageerror', e => errors.push(e.stack || e.message));
  await page.goto(URL, { waitUntil: 'domcontentloaded', timeout: 60000 });
  await page.waitForSelector('#comando .cmd', { timeout: 30000 });
  await page.screenshot({ path: path.join(OUT, '01-home.png'), fullPage: true });
  const pre = await page.evaluate(() => ({ body: document.body.innerText, legacyPrint: typeof window.v73Print, icon: !!document.getElementById('cmdRepresentacaoInstitucional') }));
  check(pre.icon, 'Ícone Representação Institucional ausente na home');
  check(!pre.body.includes('window.v73Print=function'), 'HTML exibe JavaScript v73 como texto');
  check(pre.legacyPrint === 'function', 'Rotina de impressão legada v73 não carregou');
  await page.locator('#cmdRepresentacaoInstitucional').click();
  await page.waitForSelector('#riResults table tbody tr', { timeout: 30000 });
  const n = await page.locator('#riResults table tbody tr').count();
  check(n === 843, 'Base institucional retornou ' + n + ' registros; esperado 843');
  await page.screenshot({ path: path.join(OUT, '02-representacao.png'), fullPage: true });
  await page.locator('#riRegiao').selectOption('Norte');
  await page.locator('#riUF').selectOption('RR');
  const selected = await page.locator('#riResults').innerText();
  check(/Marcos Jorge/i.test(selected), 'Marcos Jorge não aparece para RR em 2027');
  check(selected.includes('REPUBLICANOS'), 'Partido REPUBLICANOS não encontrado');
  await page.screenshot({ path: path.join(OUT, '03-roraima.png'), fullPage: true });
  const [report] = await Promise.all([page.waitForEvent('popup'), page.locator('#riReport').click()]);
  await report.waitForLoadState('domcontentloaded');
  const reportText = await report.locator('body').innerText();
  check(reportText.includes('REPRESENTAÇÃO INSTITUCIONAL'), 'Relatório institucional não abriu');
  check(reportText.includes('Marcos Jorge'), 'Relatório de RR perdeu Marcos Jorge');
  await report.screenshot({ path: path.join(OUT, '04-relatorio-institucional.png'), fullPage: true });
  await report.close();
  const [brief] = await Promise.all([page.waitForEvent('popup'), page.locator('#riBriefing').click()]);
  await brief.waitForLoadState('domcontentloaded');
  check((await brief.locator('body').innerText()).includes('BRIEFING'), 'Briefing não abriu');
  await brief.screenshot({ path: path.join(OUT, '05-briefing.png'), fullPage: true });
  await brief.close();
  await page.locator('#homeBack button').click();
  check(await page.locator('#cmdRepresentacaoInstitucional').isVisible(), 'Retorno à home falhou');
  check(!await page.locator('#representacaoInstitucionalView').isVisible(), 'Módulo permanece visível após voltar');
  await page.locator('.command-grid > button.cmd').first().click();
  check(await page.locator('#quickResult').isVisible(), 'Investimentos não abriu na tabela rápida');
  await page.screenshot({ path: path.join(OUT, '06-investimentos.png'), fullPage: true });
  await page.locator('#homeBack button').click();
  await page.locator('.command-grid > button.cmd').nth(9).click();
  check(await page.locator('#docs').isVisible(), 'Relatório Executivo legado não abriu');
  check(await page.locator('#riIncludeDocs').count() === 1, 'Checkbox opcional da representação não existe');
  await page.evaluate(() => window.doc('rel'));
  check(await page.locator('#doc').count() === 1, 'Gerador de relatório legado ausente');
  await page.screenshot({ path: path.join(OUT, '07-relatorio-legado.png'), fullPage: true });
  check(errors.length === 0, 'Erros JavaScript: ' + errors.join(' | '));
  await browser.close();
  console.log(JSON.stringify({ ok: true, registros: 843, testes: ['ícone', 'sem código visível', 'v73Print', 'dados', 'filtros', 'RR', 'relatório', 'briefing', 'voltar', 'investimentos', 'relatório legado'], screenshots: 7 }, null, 2));
}
main().catch(e => { console.error('FALHA E2E:', e.stack || e); process.exit(1); });
